using System;
using System.Collections;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Text;
using System.IO;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Widgets.MVP.Essential_Repos;

namespace HiDesktop
{
    public partial class TextBar : Form
    {
        string Path;
        Hashtable AppConfig;
        /// <summary>
        /// 让程序不显示在alt+Tab视图窗体中
        /// </summary>
        protected override CreateParams CreateParams
        {
            get
            {
                const int WS_EX_APPWINDOW = 0x40000;
                const int WS_EX_TOOLWINDOW = 0x80;
                CreateParams cp = base.CreateParams;
                cp.ExStyle &= (~WS_EX_APPWINDOW);
                cp.ExStyle |= WS_EX_TOOLWINDOW;
                cp.ExStyle |= 0x02000000;//解决闪屏问题，来自 https://blog.csdn.net/weixin_38211198/article/details/90724952
                return cp;
            }
        }
        //From https://www.cnblogs.com/darkic/p/16256294.html



        //实现自动将窗口置于底层
        //Generated by GPT-4o
        //Prompted by 幻愿Recovery
        [DllImport("user32.dll")]
        static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int X, int Y, int cx, int cy, uint uFlags);

        const uint SWP_NOMOVE = 0x0002;
        const uint SWP_NOSIZE = 0x0001;
        const int HWND_BOTTOM = 1;

        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);
            //SetWindowPos(this.Handle, new IntPtr(HWND_BOTTOM), 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE);
        }

        public TextBar(string Path)
        {

            InitializeComponent();
            this.Path = Path;

        }

        public void LoadWidget()
        {
            Hashtable htStandard = new Hashtable()
            {
                { "type", "TextBar" },
                { "font", "auto" },
                { "fontSize", "30" },
                { "opacity", "1" },
                { "topMost", "false" },
                { "text", "Config your textBar in properties file.." },
                { "location", "auto" },
                { "enabled","true" },
                { "color","#FFFFFF" },
                { "allowMove","true" },
                { "TransparencyKey","#000000" }
            };
            if (!File.Exists(Path))
            {
                Hashtable Config = htStandard;
                PropertiesHelper.Save(Path, Config);
                Log.SaveLog($"[{Path}]Created properties file.");

            }
            if (File.ReadAllText(Path) == "")
            {
                Hashtable Config = htStandard;
                PropertiesHelper.Save(Path, Config);

            }
            PropertiesHelper.AutoCheck(htStandard, Path);
            Log.SaveLog($"[{Path}]Repaired properties");
            AppConfig = PropertiesHelper.Load(Path);
            Log.SaveLog($"[{Path}]Loaded properties");
            if ((string)AppConfig["enabled"] != "true")
            {
                Log.SaveLog($"[{Path}]{Path} is not enabled.");
                this.Close();
                return;

            }

            if ((string)AppConfig["type"] != "TextBar")
            {
                Log.SaveLog($"[{Path}]{Path} is not a properties file of TextBar.");
                this.Close();
                return;
            }

            float fontSize = Convert.ToInt32(AppConfig["fontSize"]);
            Log.SaveLog($"[{Path}]FontSize set.");
            Opacity = Convert.ToDouble(AppConfig["opacity"]);
            Log.SaveLog($"[{Path}]Opacity set.");
            if ((string)AppConfig["topMost"] == "true")
            {
                TopMost = true;
                Log.SaveLog($"[{Path}]TopMost.");
            }
            else
            {
                TopMost = false;
                Log.SaveLog($"[{Path}]Not TopMost.");
            }
            if ((string)AppConfig["font"] != "auto")
            {
                Setfont((string)AppConfig["font"]);
            }




            LabelNo1.ForeColor = ColorTranslator.FromHtml((string)AppConfig["color"]);
            LabelNo1.Font = new Font(LabelNo1.Font.Name, fontSize);
            LabelNo1.Text = (string)AppConfig["text"];
            //BackColor = Color.Transparent;
            var tColor = ColorTranslator.FromHtml((string)AppConfig["TransparencyKey"]);
            BackColor = tColor;
            TransparencyKey = tColor;





            int w = SystemInformation.PrimaryMonitorSize.Width;
            int h = SystemInformation.PrimaryMonitorSize.Height;
            LabelNo1.Location = new Point(0, 0);
            Size = new Size(LabelNo1.Location.X + LabelNo1.Size.Width, LabelNo1.Size.Height);
            if ((string)AppConfig["location"] == "auto")
            {
                int startX = LabelNo1.Location.X;
                int endX = LabelNo1.Location.X + LabelNo1.Size.Width;
                int deltaX = endX - startX;
                Location = new Point(w / 2 - (deltaX) / 2, Location.Y);
            }
            else
            {
                try
                {
                    string Location = (string)AppConfig["location"];
                    if (Location == null)
                    {
                        int startX = LabelNo1.Location.X;
                        int endX = LabelNo1.Location.X + LabelNo1.Size.Width;
                        int deltaX = endX - startX;
                        this.Location = new Point(w / 2 - (deltaX) / 2, this.Location.Y);
                    }
                    else
                    {
                        this.Location = new Point(Convert.ToInt32(Location.Split(",")[0]), Convert.ToInt32(Location.Split(",")[1]));
                    }

                }
                catch
                {
                    int startX = LabelNo1.Location.X;
                    int endX = LabelNo1.Location.X + LabelNo1.Size.Width;
                    int deltaX = endX - startX;
                    Location = new Point(w / 2 - (deltaX) / 2, Location.Y);
                }
            }

        }

        public void Setfont(string path)
        {
            try
            {
                //从外部文件加载字体文件
                PrivateFontCollection font = new PrivateFontCollection();
                font.AddFontFile(path);

                //定义成新的字体对象
                FontFamily myFontFamily = new FontFamily(font.Families[0].Name, font);
                Font myFont = new Font(myFontFamily, 56F, FontStyle.Regular);

                //将字体显示到控件
                LabelNo1.Font = myFont;

            }
            catch (InvalidCastException e)
            {
                MessageBox.Show(e.Message.ToString(), "异常：", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }
        }

        [DllImport("user32.dll")]
        public static extern bool ReleaseCapture();

        [DllImport("user32.dll")]
        public static extern bool SendMessage(IntPtr hwnd, int wMsg, int wParam, int lParam);

        private void FrmMain_MouseDown(object sender, MouseEventArgs e)
        {
            if ((string)AppConfig["allowMove"] == "true")
            {
                ReleaseCapture();
                SendMessage(this.Handle, 0x0112, 0xF012, 0);
            }

        }
        protected override void OnMouseDown(MouseEventArgs e)
        {
            base.OnMouseDown(e);
            FrmMain_MouseDown(this, e);
        }


        private void OnMouseUp(object sender, MouseEventArgs e)
        {
            //AppConfig["location"] = $"{Location.X},{Location.Y}";
            //PropertiesHelper.Save(Path, AppConfig);
        }
        private void OnMouseDown(object sender, MouseEventArgs e)
        {
            base.OnMouseDown(e);
            FrmMain_MouseDown(this, e);
        }

        private void ReloadToolStripMenuItem_Click(object sender, EventArgs e)
        {
            LoadWidget();
        }

        private void SaveLocToolStripMenuItem_Click(object sender, EventArgs e)
        {
            AppConfig["location"] = $"{Location.X},{Location.Y}";
            PropertiesHelper.Save(Path, AppConfig);
            MessageBox.Show("新的位置已保存到配置文件", $"{Path} - HiDesktop", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void TextBar_Load(object sender, EventArgs e)
        {
            foreach (Control item in Controls)
            {
                item.ContextMenuStrip = Menu;
            }
            LoadWidget();
        }

        private void openPropertiesFileToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var filepath = System.IO.Path.GetFullPath(Path);
            Process p = new();
            p.StartInfo = new()
            {
                FileName = filepath,
                UseShellExecute = true
            };
            p.Start();
        }
    }
}
